services:
  # Frontend React
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - powerai-network

  # Backend FastAPI
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/powerai
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - powerai-network

  # Base de données MongoDB
  mongodb:
    image: mongo:7.0
    container_name : mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=powerai123
      - MONGO_INITDB_DATABASE=powerai
    networks:
      - powerai-network

  # Interface admin MongoDB (optionnel)
  mongo-express:
    image: mongo-express:1.0.0
    container_name : mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=powerai123
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    networks:
      - powerai-network

volumes:
  mongodb_data:

networks:
  powerai-network:
    driver: bridge